spring.application.name=Emobit-backend

# CORS 설정을 위한 프론트엔드 Origin 주소 설정
url.host.emobit=${URL_HOST_EMOBIT}

# JWT 서명 비밀키
jwt.secret=${JWT_SECRET_EMOBIT}

# oracle DB 설정
spring.datasource.url=${DB_HOST_EMOBIT}
spring.datasource.username=${DB_USER_EMOBIT}
spring.datasource.password=${DB_PASS_EMOBIT}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.oracle.net.ssl_server_dn_match=true

# JPA 설정
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

# Redis 설정
spring.data.redis.host=localhost
spring.data.redis.port=6379

# p6spy 설정
decorator.datasource.p6spy.enable-logging=true
decorator.datasource.p6spy.multiline=false
decorator.datasource.p6spy.log-format=%(category) | %(executionTime)ms | %(sqlSingleLine)